#!/usr/bin/env python3
"""
Standalone test script to verify vector DB creation, text chunking, embedding generation,
upserting to Qdrant, and querying to verify chunking and saving in DB are properly working.
"""

import sys
import os
import asyncio
import logging
import uuid
import hashlib
from typing import List, Dict, Any

# Add project root to sys.path
sys.path.insert(0, os.path.abspath(os.path.dirname(__file__)))

from backend.config import settings
from backend.services.ingestion import chunk_text, parse_pdf
from backend.services.embeddings import get_dense_embedding, tokenize_for_sparse
from backend.services.vector_store import (
    initialize_collection,
    upsert_chunks,
    get_collection_info,
    client,
    COLLECTION_NAME
)
from qdrant_client.http import models

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger("vector_db_test")

SAMPLE_DOCUMENT_TEXT = """
Antigravity Retrieval-Augmented Generation (RAG) Architecture Overview

1. Executive Summary
The GraphRAG system combines dense vector retrieval, sparse BM25 keyword matching, and Neo4j graph entity relations.
This hybrid architecture ensures high precision for specific term queries while maintaining semantic understanding across large document sets.
Vector databases store high-dimensional embeddings generated from text chunks, allowing fast nearest-neighbor similarity search.

2. Document Ingestion Pipeline
When a user uploads a document (such as a PDF or image file), the system first parses the file using PyMuPDF or Tesseract OCR.
After parsing, the extracted text is processed through a contextual chunking engine.
The chunking process splits the text into chunks of 500 characters with a 50-character overlap between adjacent chunks.
Each chunk is prefixed with a global document summary generated by an LLM to preserve macro-level context.

3. Vector Database Storage and Indexing
Qdrant is utilized as the primary vector store. Each chunk is transformed into two vector representations:
a) A 384-dimensional dense vector generated using SentenceTransformers (all-MiniLM-L6-v2) or fallback deterministic embeddings.
b) A sparse TF-IDF / BM25 vector representation for exact keyword matching.
Payload metadata attached to each point includes:
- document_id: Unique identifier for the source document.
- chunk_index: Sequential index of the chunk in the document.
- page_number: The page where the chunk content originated.
- text: The original raw chunk text.
- contextualized_text: The text with summary prepended.

4. Hybrid Retrieval and Fusion
During query execution, the user's prompt is encoded into both dense and sparse representations.
Dense search retrieves top-k semantic matches from Qdrant using Cosine distance.
Sparse search retrieves exact keyword matches using sparse vectors.
Reciprocal Rank Fusion (RRF) merges the dense and sparse search result lists using the formula RRF_score = sum(1 / (60 + rank)).
Top scoring chunks are passed through a cross-encoder reranker before being presented to the LLM as context.

5. Knowledge Graph Integration
Entities and relationships extracted from chunks are inserted into Neo4j graph database nodes and edges.
This allows sub-graph traversal up to 2 hops to discover hidden links between concepts that vector similarity alone might miss.
"""

def compute_hashed_sparse_vector(text: str) -> Dict[str, Any]:
    """
    Computes a sparse vector using deterministic token feature hashing.
    Ensures identical tokens map to the exact same index during indexing and search.
    """
    tokens = tokenize_for_sparse(text)
    if not tokens:
        return {"indices": [], "values": []}
        
    counts: Dict[int, float] = {}
    for token in tokens:
        idx = int(hashlib.md5(token.encode('utf-8')).hexdigest(), 16) % 1000000
        counts[idx] = counts.get(idx, 0.0) + 1.0
        
    indices = list(counts.keys())
    values = list(counts.values())
    return {"indices": indices, "values": values}


async def search_dense_updated(query_vector: List[float], top_k: int, doc_filter: str = None):
    filter_params = None
    if doc_filter:
        filter_params = models.Filter(
            must=[
                models.FieldCondition(
                    key="document_id",
                    match=models.MatchValue(value=doc_filter)
                )
            ]
        )
    res = await client.query_points(
        collection_name=COLLECTION_NAME,
        using="dense",
        query=query_vector,
        query_filter=filter_params,
        limit=top_k,
        with_payload=True
    )
    return res.points


async def search_sparse_updated(sparse_vector: Dict[str, Any], top_k: int, doc_filter: str = None):
    filter_params = None
    if doc_filter:
        filter_params = models.Filter(
            must=[
                models.FieldCondition(
                    key="document_id",
                    match=models.MatchValue(value=doc_filter)
                )
            ]
        )
    res = await client.query_points(
        collection_name=COLLECTION_NAME,
        using="sparse",
        query=models.SparseVector(
            indices=sparse_vector.get("indices", []),
            values=sparse_vector.get("values", [])
        ),
        query_filter=filter_params,
        limit=top_k,
        with_payload=True
    )
    return res.points


async def run_standalone_test():
    print("=" * 80)
    print("      STANDALONE VECTOR DB CHUNKING & STORAGE VERIFICATION TEST")
    print("=" * 80)

    test_doc_id = "test_doc_sample_001"
    
    # ---------------------------------------------------------
    # STEP 1: TEST CHUNKING
    # ---------------------------------------------------------
    print("\n--- STEP 1: Testing Text Chunking ---")
    chunk_size = 300
    overlap = 50
    chunks = chunk_text(SAMPLE_DOCUMENT_TEXT, chunk_size=chunk_size, overlap=overlap)
    print(f"Sample text length: {len(SAMPLE_DOCUMENT_TEXT)} chars")
    print(f"Generated {len(chunks)} chunks with chunk_size={chunk_size}, overlap={overlap}\n")
    
    chunking_passed = True
    if not chunks:
        print("[FAIL] No chunks created!")
        chunking_passed = False
    else:
        for idx, chunk in enumerate(chunks):
            print(f"  Chunk {idx} (len={len(chunk)}): {chunk[:60]}... -> ...{chunk[-40:]}")
            if not chunk or len(chunk.strip()) == 0:
                print(f"[FAIL] Empty chunk found at index {idx}")
                chunking_passed = False
    
    if chunking_passed:
        print("\n[SUCCESS] Step 1 Chunking passed!")

    # ---------------------------------------------------------
    # STEP 2: TEST CONTEXTUAL CHUNKS & EMBEDDINGS
    # ---------------------------------------------------------
    print("\n--- STEP 2: Testing Contextual Chunking & Embeddings ---")
    doc_summary = "GraphRAG system combining dense vector retrieval, sparse BM25 keyword matching, and Neo4j graph entity relations."
    raw_chunks = chunk_text(SAMPLE_DOCUMENT_TEXT, chunk_size, overlap)
    
    structured_chunks = []
    for i, chunk in enumerate(raw_chunks):
        ctx_text = f"Document Summary: {doc_summary}\n\nChunk Content:\n{chunk}"
        dense_vec = get_dense_embedding(ctx_text)
        sparse_vec = compute_hashed_sparse_vector(ctx_text)
        
        # Valid UUID string for Qdrant
        chunk_uuid = str(uuid.uuid5(uuid.NAMESPACE_DNS, f"{test_doc_id}_chunk_{i}"))
        
        structured_chunks.append({
            "id": chunk_uuid,
            "text": chunk,
            "contextualized_text": ctx_text,
            "dense_vector": dense_vec,
            "sparse_vector": sparse_vec,
            "metadata": {
                "document_id": test_doc_id,
                "chunk_index": i,
                "page_number": 1 if i < 5 else 2,
                "text": chunk,
                "contextualized_text": ctx_text
            },
            "triples": []
        })

    print(f"\nCreated {len(structured_chunks)} structured chunks.")
    
    embedding_passed = True
    for idx, sc in enumerate(structured_chunks):
        dense_vec = sc.get("dense_vector", [])
        sparse_vec = sc.get("sparse_vector", {})
        print(f"  Chunk {idx}: ID={sc['id']}, Dense dim={len(dense_vec)}, Sparse non-zero count={len(sparse_vec.get('indices', []))}")
        
        if len(dense_vec) != 384:
            print(f"[FAIL] Dense vector dimension expected 384, got {len(dense_vec)}")
            embedding_passed = False
        if "text" not in sc or not sc["text"]:
            print(f"[FAIL] 'text' missing in structured chunk {idx}")
            embedding_passed = False
            
    if embedding_passed:
        print("\n[SUCCESS] Step 2 Embeddings & Structuring passed!")

    # ---------------------------------------------------------
    # STEP 3: TEST VECTOR STORE INITIALIZATION & UPSERT
    # ---------------------------------------------------------
    print("\n--- STEP 3: Testing Qdrant Collection Initialization & Upsert ---")
    await initialize_collection()
    
    print(f"Upserting {len(structured_chunks)} chunks into Qdrant collection '{COLLECTION_NAME}'...")
    await upsert_chunks(doc_id=test_doc_id, chunks=structured_chunks)

    info = await client.get_collection(COLLECTION_NAME)
    print(f"Qdrant Collection Info: Status={info.status}, Points Count={info.points_count}")

    upsert_passed = True
    if info.points_count < len(structured_chunks):
        print(f"[FAIL] Expected at least {len(structured_chunks)} points in Qdrant, got {info.points_count}")
        upsert_passed = False
    else:
        print("\n[SUCCESS] Step 3 Vector Store Upsert passed!")

    # ---------------------------------------------------------
    # STEP 4: VERIFY SAVED PAYLOAD INTEGRITY
    # ---------------------------------------------------------
    print("\n--- STEP 4: Verifying Saved Payload Integrity ---")
    res, _ = await client.scroll(
        collection_name=COLLECTION_NAME,
        limit=10,
        with_payload=True,
        with_vectors=False
    )
    
    payload_passed = True
    for pt in res:
        print(f"  Point ID: {pt.id}")
        payload = pt.payload or {}
        print(f"    Payload keys: {list(payload.keys())}")
        if "text" not in payload or not payload["text"]:
            print("    [ERROR] 'text' is MISSING or empty in Qdrant payload!")
            payload_passed = False
        else:
            print(f"    text (len={len(payload['text'])}): {payload['text'][:50]}...")
            
        if "contextualized_text" not in payload or not payload["contextualized_text"]:
            print("    [ERROR] 'contextualized_text' is MISSING or empty in Qdrant payload!")
            payload_passed = False
            
        if "document_id" not in payload:
            print("    [ERROR] 'document_id' is MISSING in Qdrant payload!")
            payload_passed = False

    if payload_passed:
        print("\n[SUCCESS] Step 4 Payload Integrity passed!")
    else:
        print("\n[FAIL] Step 4 Payload Integrity failed - payload fields missing!")

    # ---------------------------------------------------------
    # STEP 5: TEST DENSE & SPARSE SEARCH RETRIEVAL
    # ---------------------------------------------------------
    print("\n--- STEP 5: Testing Dense & Sparse Retrieval ---")
    query_text = "What vector database is used and how are embeddings stored?"
    print(f"Query: '{query_text}'")
    
    query_dense_vec = get_dense_embedding(query_text)
    dense_results = await search_dense_updated(query_dense_vec, top_k=3, doc_filter=test_doc_id)
    
    print(f"\nDense Search Results ({len(dense_results)} hits):")
    for idx, hit in enumerate(dense_results):
        score = hit.score
        text_preview = hit.payload.get("text", "N/A")[:70]
        print(f"  Hit {idx+1} [Score: {score:.4f}] Chunk Index: {hit.payload.get('chunk_index')} | Content: {text_preview}...")

    # Sparse Search Test using token feature hashing
    query_sparse_vec = compute_hashed_sparse_vector(query_text)
    print(f"\nGenerated Query Sparse Vector: indices count={len(query_sparse_vec['indices'])}")
    sparse_results = await search_sparse_updated(query_sparse_vec, top_k=3, doc_filter=test_doc_id)
    
    print(f"Sparse Search Results ({len(sparse_results)} hits):")
    for idx, hit in enumerate(sparse_results):
        score = hit.score
        text_preview = hit.payload.get("text", "N/A")[:70]
        print(f"  Hit {idx+1} [Score: {score:.4f}] Chunk Index: {hit.payload.get('chunk_index')} | Content: {text_preview}...")

    search_passed = len(dense_results) > 0 and len(sparse_results) > 0 and payload_passed
    if search_passed:
        print("\n[SUCCESS] Step 5 Retrieval passed!")
    else:
        print("\n[FAIL] Step 5 Retrieval issue encountered.")

    print("\n" + "=" * 80)
    print("                       SUMMARY OF TEST RESULTS")
    print("=" * 80)
    print(f"  Chunking:                  {'PASS' if chunking_passed else 'FAIL'}")
    print(f"  Embedding & Structuring:   {'PASS' if embedding_passed else 'FAIL'}")
    print(f"  Qdrant Upsert:             {'PASS' if upsert_passed else 'FAIL'}")
    print(f"  Payload Integrity in DB:   {'PASS' if payload_passed else 'FAIL'}")
    print(f"  Search & Retrieval:        {'PASS' if search_passed else 'FAIL'}")
    print("=" * 80)
    
    return all([chunking_passed, embedding_passed, upsert_passed, payload_passed, search_passed])

if __name__ == "__main__":
    success = asyncio.run(run_standalone_test())
    sys.exit(0 if success else 1)
